weblight/app/mod_rest/controllers.py
# Import flask dependencies
from flask import Blueprint, request
from flask_json import as_json

from ..animation import animations
from ..extensions import app

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_rest = Blueprint('api', __name__, url_prefix='/api')


@mod_rest.route('/device', methods=['GET'])
@as_json
def device_list():
    return dict(devices=list(app.config.get('DEVICES').keys()))


@mod_rest.route('/device/<device>/on', methods=['GET'])
@as_json
def device_on(device):
    devices = app.config.get('DEVICES')
    if device not in devices:
        return dict(), 404

    device = devices[device]

    device.on()
    return dict()


@mod_rest.route('/device/<device>/off', methods=['GET'])
@as_json
def device_off(device):
    devices = app.config.get('DEVICES')
    if device not in devices:
        return dict(), 404

    device = devices[device]

    device.off()
    return dict()


@mod_rest.route('/device/<device>/animation', methods=['GET'])
@as_json
def device_animation(device):
    devices = app.config.get('DEVICES')
    if device not in devices:
        return dict(msg='device not found'), 404
    device = devices[device]

    animation = request.args.get('animation')
    if animation not in animations:
        return dict(msg='animation not found'), 404

    args = request.args.copy()

    device.set_anim(animations[animation], args=args)

    return dict()

@mod_rest.route('/device/<device>/brightness', methods=['GET'])
@as_json
def device_brightness(device):
    devices = app.config.get('DEVICES')
    if device not in devices:
        return dict(msg='device not found'), 404
    device = devices[device]

    brightness = float(request.args.get('brightness'))
    device.set_brightness(brightness)

    return dict()

weblight/app/templates/admin_base.html
{% import 'admin/layout.html' as layout with context -%}
{% extends 'admin/base.html' %}

{% block page_body %}
  {% if current_user.is_authenticated %}
    {{  super() }}
  {% else %}
    <p>You need to <a href="{{ url_for('auth.login') }}">log in</a>!</p>
  {% endif %}
{% endblock %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="navbar-text btn-group pull-right">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        <i class="glyphicon glyphicon-user"></i>
        {% if current_user.first_name -%}
        {{ current_user.first_name }}
        {% else -%}
        {{ current_user.email }}
        {%- endif %}<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
        <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock %}

weblight/app/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}test{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"  type="text/css" ?>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" type="text/css" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css" />
    </head>
    <body>
        <div class="container" >
            {% block content %}{% endblock %}
        </div>
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.form.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/index.js') }}"></script>
        <script type="text/javascript">
            {% block javascript %}{% endblock %}
        </script>
    </body>
</html>

weblight/app/templates/index.html
{% extends 'base.html' %}

{% block title %}index{% endblock %}

{% block content %}
    <div class="row">
    {% for name,device in devices.items() %}
        <div class="col-md-6">
            <h2>{{ name }}</h2>
            <a class="btn btn-default" href="{{ url_for("api.device_on",device=name) }}">On</a>
            <a class="btn btn-default" href="{{ url_for("api.device_off",device=name) }}">Off</a>
            <div >
                <form action="{{ url_for("api.device_animation",device=name) }}">
                    <h3>Animation</h3>
                    <div class="form-group">
                        {{ form.animation.label }}
                        {{ form.animation(class='form-control') }}
                    </div>
                    <div class="form-group">
                        {{ form.brightness.label }}
                        {{ form.brightness(type='range',min=0,max=1,step=0.01) }}
                    </div>
                    <div class="form-group">
                        {{ form.speed.label }}
                        {{ form.speed(class='form-control') }}
                    </div>
                    <div class="form-group">
                        {{ form.size.label }}
                        {{ form.size(class='form-control') }}
                    </div>
                    <div class="form-group">
                        {{ form.color.label }}
                        {{ form.color(class='form-control',type='color') }}
                    </div>
                    <button type="submit" class="btn btn-default">set</button>
                </form>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

{% block javascript %}
index.Init();
{% endblock %}